
services:
  postgres-devilery:
    image: postgres:15-alpine
    container_name: delivery-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-delivery:
    image: redis:latest
    container_name: delivery-redis
    restart: always
    command: ["redis-server", "--requirepass", "your_redis_pass"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
    
    
